[package]
name = "penglai-rt"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sbi-spec = { version = "0.0.8", path = "../sbi-spec" }
penglai = { version = "0.0.0", path = "../penglai" }
